/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HazardLayersRouteImport } from './routes/hazard-layers'
import { Route as MissionLabRouteImport } from './routes/mission-lab'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SolBySolRouteImport } from './routes/sol-by-sol'
import { Route as ApiMarsAdvisorRouteImport } from './routes/api/mars-advisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HazardLayersRoute = HazardLayersRouteImport.update({
  id: '/hazard-layers',
  path: '/hazard-layers',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionLabRoute = MissionLabRouteImport.update({
  id: '/mission-lab',
  path: '/mission-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SolBySolRoute = SolBySolRouteImport.update({
  id: '/sol-by-sol',
  path: '/sol-by-sol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarsAdvisorRoute = ApiMarsAdvisorRouteImport.update({
  id: '/api/mars-advisor',
  path: '/api/mars-advisor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hazard-layers': typeof HazardLayersRoute
  '/mission-lab': typeof MissionLabRoute
  '/protocols': typeof ProtocolsRoute
  '/resources': typeof ResourcesRoute
  '/sol-by-sol': typeof SolBySolRoute
  '/api/mars-advisor': typeof ApiMarsAdvisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hazard-layers': typeof HazardLayersRoute
  '/mission-lab': typeof MissionLabRoute
  '/protocols': typeof ProtocolsRoute
  '/resources': typeof ResourcesRoute
  '/sol-by-sol': typeof SolBySolRoute
  '/api/mars-advisor': typeof ApiMarsAdvisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hazard-layers': typeof HazardLayersRoute
  '/mission-lab': typeof MissionLabRoute
  '/protocols': typeof ProtocolsRoute
  '/resources': typeof ResourcesRoute
  '/sol-by-sol': typeof SolBySolRoute
  '/api/mars-advisor': typeof ApiMarsAdvisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hazard-layers'
    | '/mission-lab'
    | '/protocols'
    | '/resources'
    | '/sol-by-sol'
    | '/api/mars-advisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hazard-layers'
    | '/mission-lab'
    | '/protocols'
    | '/resources'
    | '/sol-by-sol'
    | '/api/mars-advisor'
  id:
    | '__root__'
    | '/'
    | '/hazard-layers'
    | '/mission-lab'
    | '/protocols'
    | '/resources'
    | '/sol-by-sol'
    | '/api/mars-advisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HazardLayersRoute: typeof HazardLayersRoute
  MissionLabRoute: typeof MissionLabRoute
  ProtocolsRoute: typeof ProtocolsRoute
  ResourcesRoute: typeof ResourcesRoute
  SolBySolRoute: typeof SolBySolRoute
  ApiMarsAdvisorRoute: typeof ApiMarsAdvisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazard-layers': {
      id: '/hazard-layers'
      path: '/hazard-layers'
      fullPath: '/hazard-layers'
      preLoaderRoute: typeof HazardLayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-lab': {
      id: '/mission-lab'
      path: '/mission-lab'
      fullPath: '/mission-lab'
      preLoaderRoute: typeof MissionLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sol-by-sol': {
      id: '/sol-by-sol'
      path: '/sol-by-sol'
      fullPath: '/sol-by-sol'
      preLoaderRoute: typeof SolBySolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mars-advisor': {
      id: '/api/mars-advisor'
      path: '/api/mars-advisor'
      fullPath: '/api/mars-advisor'
      preLoaderRoute: typeof ApiMarsAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HazardLayersRoute: HazardLayersRoute,
  MissionLabRoute: MissionLabRoute,
  ProtocolsRoute: ProtocolsRoute,
  ResourcesRoute: ResourcesRoute,
  SolBySolRoute: SolBySolRoute,
  ApiMarsAdvisorRoute: ApiMarsAdvisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
